### ISSUE TITLE
Thunderstore 自动安装模组卡在100%

### ISSUE THREAD

**Issue by bakashigure** [XoF-eLtTiL/Lethal_Company_Traditional_Chinese_Localization#4]
![image](https://github.com/XoF-eLtTiL/Lethal_Company_Traditional_Chinese_Localization/assets/33803916/bf8deb55-a8b1-40a0-b72d-57985d555852)

使用Thunderstore自动安装模组，使用默认配置`Default`

卡在100%没有后续，尝试过完全清空游戏安装目录然后重新安装，或者清空Thunderstore的缓存，不起作用。

没有找到mod安装的日志位置，有日志可能可以辅助排查，目前看起来mod已经成功放进`plugins`文件夹，但是Thunderstore没有进行后续的操作，在已安装的mod列表里也没有繁中汉化mod。

**Comment by bakashigure** [comment]
找到了日志
```
2024-01-01 23:14:03,052 (INFO) ================== new session ==================
2024-01-01 23:14:03,052 (ERROR) </dist/js/chunk-vendors.9683cec1.js> (:418) - user not logged in
2024-01-01 23:14:03,172 (WARN) </dist/js/chunk-vendors.9683cec1.js> (:418) - The function |overwolf.utils.getMonitorsList| requires the |DesktopStreaming| permission.
2024-01-01 23:14:59,083 (ERROR) </dist/js/chunk-vendors.9683cec1.js> (:418) - Unhandled Promise rejection: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bakashigure\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Default\BepInEx\plugins\XoFKon-Lethal_Company_Traditional_Chinese_Localization\XUnity.AutoTranslator\Translators\FullNET\XUnity.AutoTranslator.Plugin.ExtProtocol.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at r2io.FileOperations.<>c__DisplayClass12_0.<CopyFile>b__1()
   at r2io.Utilities.RunSafe(String appName, String appId, String pathFrom, String pathTo, Func`1 runFunc) ; Zone: <root> ; Task: Promise.then ; Value: Failed to copy file: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bakashigure\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Default\BepInEx\plugins\XoFKon-Lethal_Company_Traditional_Chinese_Localization\XUnity.AutoTranslator\Translators\FullNET\XUnity.AutoTranslator.Plugin.ExtProtocol.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at r2io.FileOperations.<>c__DisplayClass12_0.<CopyFile>b__1()
   at r2io.Utilities.RunSafe(String appName, String appId, String pathFrom, String pathTo, Func`1 runFunc) Failed to copy file: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bakashigure\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Default\BepInEx\plugins\XoFKon-Lethal_Company_Traditional_Chinese_Localization\XUnity.AutoTranslator\Translators\FullNET\XUnity.AutoTranslator.Plugin.ExtProtocol.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at r2io.FileOperations.<>c__DisplayClass12_0.<CopyFile>b__1()
   at r2io.Utilities.RunSafe(String appName, String appId, String pathFrom, String pathTo, Func`1 runFunc)
    at overwolf-extension://ahpflogoookodlegojjphcjpjaejgghjnfcdjdmi/dist/js/app.f5c822fb.js:1:453535
2024-01-01 23:14:59,088 (ERROR) </dist/js/chunk-vendors.9683cec1.js> (:259) - Uncaught (in promise) Failed to copy file: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bakashigure\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Default\BepInEx\plugins\XoFKon-Lethal_Company_Traditional_Chinese_Localization\XUnity.AutoTranslator\Translators\FullNET\XUnity.AutoTranslator.Plugin.ExtProtocol.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at r2io.FileOperations.<>c__DisplayClass12_0.<CopyFile>b__1()
   at r2io.Utilities.RunSafe(String appName, String appId, String pathFrom, String pathTo, Func`1 runFunc)

```

在cache目录下这些`DLL`存在，但在`profiles`内看起来缺失了

![image](https://github.com/XoF-eLtTiL/Lethal_Company_Traditional_Chinese_Localization/assets/33803916/70cb8429-a9ff-4905-bda2-f058ad39a3a8)

**Comment by XoF-eLtTiL** [comment]
> 找到了日志
> 
> ```
> 2024-01-01 23:14:03,052 (INFO) ================== new session ==================
> 2024-01-01 23:14:03,052 (ERROR) </dist/js/chunk-vendors.9683cec1.js> (:418) - user not logged in
> 2024-01-01 23:14:03,172 (WARN) </dist/js/chunk-vendors.9683cec1.js> (:418) - The function |overwolf.utils.getMonitorsList| requires the |DesktopStreaming| permission.
> 2024-01-01 23:14:59,083 (ERROR) </dist/js/chunk-vendors.9683cec1.js> (:418) - Unhandled Promise rejection: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bakashigure\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Default\BepInEx\plugins\XoFKon-Lethal_Company_Traditional_Chinese_Localization\XUnity.AutoTranslator\Translators\FullNET\XUnity.AutoTranslator.Plugin.ExtProtocol.dll'.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
>    at r2io.FileOperations.<>c__DisplayClass12_0.<CopyFile>b__1()
>    at r2io.Utilities.RunSafe(String appName, String appId, String pathFrom, String pathTo, Func`1 runFunc) ; Zone: <root> ; Task: Promise.then ; Value: Failed to copy file: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bakashigure\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Default\BepInEx\plugins\XoFKon-Lethal_Company_Traditional_Chinese_Localization\XUnity.AutoTranslator\Translators\FullNET\XUnity.AutoTranslator.Plugin.ExtProtocol.dll'.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
>    at r2io.FileOperations.<>c__DisplayClass12_0.<CopyFile>b__1()
>    at r2io.Utilities.RunSafe(String appName, String appId, String pathFrom, String pathTo, Func`1 runFunc) Failed to copy file: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bakashigure\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Default\BepInEx\plugins\XoFKon-Lethal_Company_Traditional_Chinese_Localization\XUnity.AutoTranslator\Translators\FullNET\XUnity.AutoTranslator.Plugin.ExtProtocol.dll'.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
>    at r2io.FileOperations.<>c__DisplayClass12_0.<CopyFile>b__1()
>    at r2io.Utilities.RunSafe(String appName, String appId, String pathFrom, String pathTo, Func`1 runFunc)
>     at overwolf-extension://ahpflogoookodlegojjphcjpjaejgghjnfcdjdmi/dist/js/app.f5c822fb.js:1:453535
> 2024-01-01 23:14:59,088 (ERROR) </dist/js/chunk-vendors.9683cec1.js> (:259) - Uncaught (in promise) Failed to copy file: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\bakashigure\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Default\BepInEx\plugins\XoFKon-Lethal_Company_Traditional_Chinese_Localization\XUnity.AutoTranslator\Translators\FullNET\XUnity.AutoTranslator.Plugin.ExtProtocol.dll'.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
>    at r2io.FileOperations.<>c__DisplayClass12_0.<CopyFile>b__1()
>    at r2io.Utilities.RunSafe(String appName, String appId, String pathFrom, String pathTo, Func`1 runFunc)
> ```
> 
> 在cache目录下这些`DLL`存在，但在`profiles`内看起来缺失了
> 
> ![image](https://private-user-images.githubusercontent.com/33803916/293593876-70cb8429-a9ff-4905-bda2-f058ad39a3a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMjcwNTAsIm5iZiI6MTcwNDEyNjc1MCwicGF0aCI6Ii8zMzgwMzkxNi8yOTM1OTM4NzYtNzBjYjg0MjktYTlmZi00OTA1LWJkYTItZjA1OGFkMzlhM2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDE2MzIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMTFlYTNhNzI5MDhhNGU5YTUxMzE4YTIwNjBhM2FiNDM1YjFlMTQ5MzAxNGE2N2NhNzAxYTI1YWRiYmJhNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.goxg8BjH9xLEAFn9GT31PJVJtCnIgMfYGZiEPKmfC2Q)
我在想這是是否跟安裝包名稱有關係，這個我會觀察看看

**Comment by Shir0Kun** [comment]
想問樓主我也是有面臨這個問題就是繁體包卡100% 但是如果我開一個新檔案然後從%appdata%拷貝模組去DEFAULT的話能行就是游戲能順利進行就是繁體包會出現紅色代碼
![Screenshot 2023-12-28 200935](https://github.com/XoF-eLtTiL/Lethal_Company_Traditional_Chinese_Localization/assets/155505837/9a7a87c9-cc64-4078-8c46-2ea5bdabaf9c)
![Screenshot 2023-12-28 201127](https://github.com/XoF-eLtTiL/Lethal_Company_Traditional_Chinese_Localization/assets/155505837/923a3a15-2bd8-4803-8fc6-0a5692e30442)

**Comment by Shir0Kun** [comment]
想問樓主我也是有面臨這個問題就是繁體包卡100% 但是如果我開一個新檔案從%appdata%拷貝去DEFAULT的話能行就是游戲能順利進行就是繁體包會出現紅色代碼
![Screenshot 2024-01-03 161042](https://github.com/XoF-eLtTiL/Lethal_Company_Traditional_Chinese_Localization/assets/155505837/b6045427-3922-42e6-8614-48d7deb22650)
![Screenshot 2024-01-03 161203](https://github.com/XoF-eLtTiL/Lethal_Company_Traditional_Chinese_Localization/assets/155505837/756f6d5d-8491-4223-83c6-ee440dad1051)

**Comment by XoF-eLtTiL** [comment]
> 想問我也是有面臨這個問題就是繁體包卡100% 但是如果我開一個新檔案從%appdata%拷貝去DEFAULT的話能行就是游戲能順利進行就是繁體包會出現紅色代碼 當時如果想在裝模組的話要開新檔案 在DEFAULT的話就會卡100% ![Screenshot 2024-01-03 161042](https://private-user-images.githubusercontent.com/155505837/293862053-b6045427-3922-42e6-8614-48d7deb22650.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MDE5MjAsIm5iZiI6MTcwNDYwMTYyMCwicGF0aCI6Ii8xNTU1MDU4MzcvMjkzODYyMDUzLWI2MDQ1NDI3LTM5MjItNDJlNi04NjE0LTQ4ZDdkZWIyMjY1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QwNDI3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTM5YjlmNmM5M2M2NTJlZjI2OWZkOTQwODIzYTA3MTMzMTU3NWI4ZDQyMThjYWQ1NjI2YjBiNmU3Y2YyOWM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bb5YFVy-oFLpZ_eZwXGalwRV4rkftUDPD46M0TY-kM4) ![Screenshot 2024-01-03 161203](https://private-user-images.githubusercontent.com/155505837/293862066-756f6d5d-8491-4223-83c6-ee440dad1051.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MDE5MjAsIm5iZiI6MTcwNDYwMTYyMCwicGF0aCI6Ii8xNTU1MDU4MzcvMjkzODYyMDY2LTc1NmY2ZDVkLTg0OTEtNDIyMy04M2M2LWVlNDQwZGFkMTA1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwN1QwNDI3MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMzY0ZDMxY2M0MjUyNTI1YjY5OGM3OWMyMzI3MjdlMWIwZTFlYmQxYzgyZmFkMmYzZmIxYjYxNDE0M2EyYmYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9vTa4iPUnlyBpdfDtlJpKPBmHsF-6IyQotGgCJAzS6s)


這個目前問題出在 XUnity 翻譯插件上，已經正在跟官方回報了
